/**
 * Loads the fetched attack-cost dataset from `data/standard/attack-costs.json`.
 * This file is generated by `scripts/fetchAttackCosts.ts` against the Pokémon
 * TCG API and contains authoritative cost arrays for every Pokémon used in
 * the tournament decks.
 *
 * Lookup priority (in `corpusDeckBuilder.buildAttacks`):
 *   1. This fetched dataset                 ← authoritative
 *   2. `knownAttackCosts.ts` hand-curated   ← legacy, kept for any gaps
 *   3. 1-of-primary-type fallback           ← last resort
 */

import dataset from "../../../data/standard/attack-costs.json";

interface AttackCostJsonEntry {
  pokemonName: string;
  apiId: string;
  set: string;
  number: string;
  attacks: {
    name: string;
    cost: string[];
    convertedEnergyCost: number;
    damage: string;
  }[];
}

const DATA = dataset as AttackCostJsonEntry[];

/** Build an in-memory index keyed by lower-cased pokemonName + attackName. */
const INDEX: Map<string, Map<string, { cost: string[]; convertedEnergyCost: number }>> =
  new Map();

for (const entry of DATA) {
  const nameKey = entry.pokemonName.toLowerCase();
  let attackMap = INDEX.get(nameKey);
  if (!attackMap) {
    attackMap = new Map();
    INDEX.set(nameKey, attackMap);
  }
  for (const attack of entry.attacks) {
    attackMap.set(attack.name, {
      cost: attack.cost,
      convertedEnergyCost: attack.convertedEnergyCost,
    });
  }
}

/**
 * Lookup an attack's authoritative cost by Pokémon name + attack name.
 * Returns `null` if the dataset doesn't cover the pair.
 *
 * Matching is exact on the Pokémon's lower-cased name as printed on the
 * card (e.g. "dragapult ex"), but substring-tolerant so deck-builder
 * inputs that include qualifiers still resolve.
 */
export function lookupFetchedAttackCost(
  pokemonName: string,
  attackName: string,
): { cost: string[]; convertedEnergyCost: number } | null {
  const nameKey = pokemonName.toLowerCase();

  // First try exact name match.
  const exact = INDEX.get(nameKey);
  if (exact) {
    const found = exact.get(attackName);
    if (found) return found;
  }

  // Fallback: substring match. Useful when the card-builder passes a name
  // with extra qualifiers (e.g. set prefix).
  for (const [name, attacks] of INDEX) {
    if (nameKey.includes(name) || name.includes(nameKey)) {
      const found = attacks.get(attackName);
      if (found) return found;
    }
  }

  return null;
}

/** Diagnostic: total number of (Pokémon, attack) pairs in the dataset. */
export function getFetchedDatasetSize(): number {
  let total = 0;
  for (const attacks of INDEX.values()) total += attacks.size;
  return total;
}
