/**
 * Hand-curated attack-cost overrides — backstop only.
 *
 * The PRIMARY source of authoritative cost data is now
 * `data/standard/attack-costs.json` (generated by
 * `scripts/fetchAttackCosts.ts`, served via `attackCostsData.ts`).
 *
 * This file only kicks in when:
 *   • The fetched dataset doesn't cover the Pokémon yet (API failures, new
 *     cards), AND
 *   • The corpus index also doesn't have cost data.
 *
 * As of the first full batch fetch, every meta-deck Pokémon is covered by
 * the fetched dataset, so this file is currently empty. Keep it that way
 * unless a specific case demands a hand-curated entry — earlier "guesses"
 * proved consistently wrong (Articuno's Dark Frost was [Water, C, C], not
 * just [Water]; Honchkrow's Rocket Feathers was [C, C], not [D, C]).
 */

export interface KnownAttackCost {
  cost: string[];
  /** Optional explicit converted cost; otherwise derived from cost.length. */
  convertedEnergyCost?: number;
  /** Mark unverified entries clearly so future audits can prioritise them. */
  unverified?: true;
}

// Currently empty — fetched dataset covers all meta cards.
const VERIFIED: Record<string, Record<string, KnownAttackCost>> = {};

/**
 * Look up the canonical cost for a (pokemonName, attackName) pair.
 * Returns `null` if the attack is not in the override table — the caller
 * should fall back to its default cost-inference logic.
 */
export function lookupAttackCost(
  pokemonName: string,
  attackName: string,
): KnownAttackCost | null {
  const nameKey = pokemonName.toLowerCase();
  for (const [keyword, attacks] of Object.entries(VERIFIED)) {
    if (nameKey.includes(keyword)) {
      const found = attacks[attackName];
      if (found) return found;
    }
  }
  return null;
}
