import type { ParsedEffect } from "./types";

const CLAUSE_MAP = new Map<string, ParsedEffect | null>([
  ["this attack does 110 damage to 3 of your opponent's pokémon.", {"kind":"damage_multi_opponent","count":3,"amount":110}],
  ["before doing damage, discard all pokémon tools and special energy from your opponent's active pokémon.", {"kind":"before_damage_discard_opponent_tools_special"}],
  ["put this pokémon and all attached cards into your deck.", {"kind":"shuffle_self_to_deck"}],
  ["during your next turn, your pokémon can't attack.", {"kind":"cant_attack_all_yours_next_turn"}],
  ["put 8 damage counters instead of 3 on that pokémon for this special condition.", {"kind":"special_condition_extra_counters","counters":8}],
  ["if you have exactly 1 prize card remaining, your opponent's active pokémon is now paralyzed.", {"kind":"status_if_exact_prizes","prizes":1,"status":"Paralyzed"}],
  ["put a pokémon from your discard pile into your hand.", {"kind":"recover_pokemon_from_discard","count":1,"nameFilter":"Pokémon"}],
  ["discard the top card of your deck, and if that card is a pokémon that doesn't have a rule box, choose 1 of its attacks and use it as this attack.", {"kind":"mill_copy_pokemon_attack"}],
  ["each player draws 3 cards.", {"kind":"draw_both_players","count":3}],
  ["if any of your benched cubone have any damage counters on them, this attack does 120 more damage.", {"kind":"damage_bonus_if_benched_named_damaged","nameFilter":"cubone","amount":120}],
  ["(your opponent chooses the new active pokémon.) if you do, this attack does 160 damage to the new active pokémon.", {"kind":"damage_after_switch","amount":160}],
  ["before doing damage, discard all pokémon tools from this pokémon.", {"kind":"before_damage_discard_self_tools"}],
  ["if you can't discard any, this attack does nothing.", {"kind":"attack_fails_if_cant_discard"}],
  ["if the retreat cost of your opponent's active pokémon is colorlesscolorless or more, this attack does 110 more damage.", {"kind":"damage_bonus_if_retreat_cost","minCost":"colorlesscolorless","amount":110}],
  ["if there are 3 or fewer cards in your deck, this attack does 200 more damage.", {"kind":"damage_bonus_if_deck_at_most","maxCards":3,"amount":200}],
  ["if there are 3 or fewer cards in your deck, this attack also does 120 damage to 2 of your opponent's benched pokémon.", {"kind":"damage_bonus_and_bench_if_deck_at_most","maxCards":3,"benchDamage":120}],
  ["discard all item cards and pokémon tool cards you find there.", null],
  ["put a trainer card from your discard pile into your hand.", {"kind":"recover_trainer_from_discard"}],
  ["devolve 1 of your opponent's evolved pokémon by putting the highest stage evolution card on it into your opponent's hand.", {"kind":"devolve_opponent"}],
  ["both active pokémon are knocked out.", {"kind":"ko_both_active"}],
  ["if the defending pokémon is a basic pokémon, it can't attack during your opponent's next turn.", {"kind":"cant_attack_defending_if_basic_next_turn"}],
  ["attach an energy card from your discard pile to this pokémon.", {"kind":"attach_energy_from_discard","count":1,"energyType":"Any","target":"self"}],
  ["if 1 of your other ancient pokémon used an attack during your last turn, this attack does 150 more damage.", {"kind":"damage_bonus_if_team_attack_last_turn","nameFilter":"ancient","amount":150}],
  ["attach up to 3 energy cards from your opponent's discard pile to their pokémon in any way you like.", {"kind":"attach_opponent_discard_energy","count":3}],
  ["discard an energy from your opponent's active pokémon ex.", {"kind":"discard_energy","count":1,"from":"opponent_active"}],
  ["if 1 of them is heads, this attack does 20 more damage.", {"kind":"coin_tier_damage","heads":1,"amount":20}],
  ["if 2 of them are heads, this attack does 50 more damage.", {"kind":"coin_tier_damage","heads":2,"amount":50}],
  ["if all of them are heads, this attack does 80 more damage.", {"kind":"coin_tier_damage","heads":99,"amount":80}],
  ["until the end of your next turn, the defending pokémon's weakness is now colorless.", {"kind":"override_defender_weakness_next_turn","weaknessType":"Colorless"}],
  ["you can use this attack only if this pokémon used rollout during your last turn.", {"kind":"cant_use_unless_last_attack","attackName":"rollout"}],
  ["if at least 2 of them are heads, your opponent's active pokémon is now paralyzed.", {"kind":"coin_min_heads_status","minHeads":2,"status":"Paralyzed"}],
  ["if you discarded any cards in this way, this attack does 120 more damage.", {"kind":"damage_bonus_if_discarded_any","amount":120}],
  ["this pokémon does 100 damage to itself.", {"kind":"self_recoil","amount":100}],
  ["if you discarded a pokémon tool in this way, your opponent's active pokémon is now paralyzed.", {"kind":"status_if_discarded_tool","status":"Paralyzed"}],
  ["then, draw a card for each card in your opponent's hand.", {"kind":"draw_per_opponent_hand"}],
  ["if beldum and metang are on your bench, this attack does 150 more damage.", {"kind":"damage_bonus_if_bench_names","names":["Beldum","Metang"],"amount":150}],
  ["if you use this attack when you have exactly 1 prize card remaining, you win this game.", {"kind":"win_if_exact_prizes","prizes":1}],
  ["choose 2 of your opponent's pokémon and put 3 damage counters on each of them.", {"kind":"place_counters_on_opponent","count":2,"counters":3}],
  ["your opponent reveals their hand, and you choose a card you find there and put it on the bottom of their deck.", {"kind":"bottom_deck_opponent_hand_card"}],
  ["discard all energy from this pokémon, and this attack does 120 damage to 1 of your opponent's pokémon.", {"kind":"discard_all_self_energy_damage","amount":120}],
  ["both active pokémon are now asleep.", {"kind":"dual_status_both_active","status":"Asleep"}],
  ["look at 1 of your opponent's face-down prize cards.", {"kind":"look_opponent_prize"}],
  ["discard the top 7 cards of your deck, and this attack does 70 damage for each misty's pokémon that you discarded in this way.", {"kind":"mill_self_named_discard_damage","count":7,"perCard":70,"nameFilter":"misty's pokémon"}],
  ["before doing damage, you may attach any number of basic water energy cards from your hand to this pokémon.", {"kind":"before_damage_attach_hand_energy","energyType":"Water"}],
  ["your opponent flips a coin for each of their benched pokémon.", {"kind":"opponent_coin_each_bench"}],
  ["this attack does 80 damage to your opponent's active pokémon for each tails.", {"kind":"coin_tails_damage_active","perTails":80}],
  ["this attack also does 40 damage to each benched pokémon that has any damage counters on it (both yours and your opponent's).", {"kind":"damage_damaged_bench_each","amount":40}],
  ["this attack does 30 damage to each of your opponent's pokémon.", {"kind":"damage_each_opponent_pokemon","amount":30}],
  ["choose up to 2 of your darkness pokémon.", {"kind":"choose_yours_typed","count":2,"typeFilter":"Darkness"}],
  ["for each of those pokémon, search your deck for a card that evolves from that pokémon and put it onto that pokémon to evolve it.", null],
  ["if a pokémon that has \"nidoking\" in its name is on your bench, this attack does 120 more damage.", {"kind":"damage_bonus_if_bench_name","nameFilter":"nidoking","amount":120}],
  ["at the end of your opponent's next turn, discard the defending pokémon and all attached cards.", {"kind":"delayed_discard_defender"}],
  ["if you have the same number of cards in your hand as your opponent, this attack does 90 more damage.", {"kind":"damage_bonus_if_hand_equal","amount":90}],
  ["attach a basic energy card from your hand to this pokémon.", {"kind":"attach_basic_energy_from_hand","energyType":"Any","target":"self"}],
  ["if you have a stadium in play, this attack does 50 more damage.", {"kind":"damage_bonus_if_stadium","amount":50}],
  ["discard the top card of your deck, and if that card is a supporter card, use the effect of that card as the effect of this attack.", {"kind":"mill_copy_supporter_attack"}],
  ["put 2 fire energy attached to this pokémon into your hand.", {"kind":"return_typed_energy_to_hand","energyType":"Fire"}],
  ["then, shuffle those cards into your deck.", null],
  ["this attack does 20 damage to each of your opponent's pokémon.", {"kind":"damage_each_opponent_pokemon","amount":20}],
  ["this attack does 60 less damage for each energy attached to your opponent's active pokémon.", {"kind":"damage_less_per_opponent_active_energy","perEnergy":60}],
  ["if both of them are heads, heal all damage from 1 of your pokémon.", {"kind":"coin_both_heads_heal_one"}],
  ["if both of them are heads, this attack does 100 more damage.", {"kind":"coin_both_heads_damage_bonus","amount":100}],
  ["this attack does 20 damage to 1 of your opponent's pokémon for each grass energy attached to this pokémon.", {"kind":"damage_multi_opponent","count":1,"amount":20}],
  ["place 1 damage counter on 1 of your opponent's pokémon.", {"kind":"damage","amount":10,"target":"opponent_bench_choose","applyWeaknessRes":false}],
  ["if you have any stage 2 darkness pokémon on your bench, this attack does 70 more damage.", {"kind":"damage_bonus_if_bench_type_stage","typeFilter":"Darkness","stage":2,"amount":70}],
  ["attach an amount of basic energy up to the number of heads from your discard pile to your benched pokémon in any way you like.", {"kind":"coin_attach_energy_from_discard","energyType":"Any","target":"benched"}],
  ["discard all energy from this pokémon and place 12 damage counters on 1 of your opponent's pokémon.", {"kind":"discard_all_self_place_counters","counters":12}],
  ["if you played a supporter card that has \"team rocket\" in its name from your hand during this turn, this attack does 100 more damage.", {"kind":"damage_bonus_if_played_named_supporter","nameFilter":"a supporter card that has \"team rocket\" in its name","amount":100}],
  ["if all of them are heads, knock out 1 of your opponent's pokémon.", {"kind":"coin_all_heads_ko_opponent"}],
  ["double the number of damage counters on each of your opponent's pokémon.", {"kind":"double_opponent_counters"}],
  ["if any of your benched pancham have any damage counters on them, this attack does 120 more damage.", {"kind":"damage_bonus_if_benched_named_damaged","nameFilter":"pancham","amount":120}],
  ["if rosa's encouragement is in your discard pile, this attack does 150 more damage.", {"kind":"damage_bonus_if_card_in_discard","nameFilter":"Rosa's Encouragement","amount":150}],
  ["discard all energy from this pokémon, and this attack does 90 damage to 1 of your opponent's pokémon.", {"kind":"discard_all_self_energy_damage","amount":90}],
  ["if you played tarragon from your hand during this turn, discard the top 3 cards of your opponent's deck.", {"kind":"mill_opponent_if_played_named","nameFilter":"tarragon","count":3}],
  ["discard random cards from your opponent's hand until they have 5 cards in their hand.", {"kind":"discard_hand_until_count","targetCount":5}],
  ["move all damage counters from 1 of your benched pokémon to your opponent's active pokémon.", {"kind":"move_counters_bench_to_opponent"}],
  ["if either of them is tails, that attack doesn't happen.", null],
  ["each player may attach up to 3 basic energy cards from their hand to their pokémon in any way they like.", {"kind":"each_player_attach_energy","count":3}],
  ["your opponent does this first.", null],
  ["discard the top 6 cards of your deck, and this attack does 60 damage for each basic water energy card you discarded in this way.", {"kind":"mill_self_typed_discard_damage","count":6,"perCard":60,"energyType":"Water"}],
  ["if you played emma from your hand during this turn, this attack does 60 more damage.", {"kind":"damage_bonus_if_played_named_supporter","nameFilter":"emma","amount":60}],
  ["this pokémon gets +50 hp for each prize card your opponent has taken.", {"kind":"hp_bonus_per_opponent_prize","perPrize":50}],
  ["whenever your opponent's active pokémon moves to the bench during their turn, their new active pokémon is now burned.", {"kind":"burn_on_opponent_switch"}],
  ["your opponent's active evolution pokémon's retreat cost is colorless more.", {"kind":"opponent_retreat_cost_increase","amount":1}],
  ["have each player draw a card.", {"kind":"draw_both_players","count":1}],
  ["your opponent's pokémon in play and all attached cards can't be put into your opponent's hand.", {"kind":"cant_return_to_hand"}],
  ["when this pokémon moves from the active spot to the bench, you may search your deck for a palafin ex and switch it with this pokémon.", {"kind":"switch_to_named_on_retreat","nameFilter":"palafin ex"}],
  ["any attached cards, damage counters, special conditions, turns in play, and any other effects remain on the new pokémon.", null],
  ["if you switched a pokémon in this way, put this card into your deck.", {"kind":"shuffle_self_if_switched_on_retreat"}],
  ["attacks used by this pokémon do 50 more damage to your opponent's active pokémon that has an ability (before applying weakness and resistance).", {"kind":"damage_bonus_vs_ability_active","amount":50}],
  ["if you played janine's secret art from your hand this turn, you may draw cards until you have 8 cards in your hand.", {"kind":"draw_until_if_played_supporter","nameFilter":"janine's secret art","targetCount":8}],
  ["you must put a card from your hand on the bottom of your deck in order to use this ability.", {"kind":"require_bottom_deck_hand_for_ability"}],
  ["if you have any tera pokémon in play, this pokémon can use the double-edge attack for psychic.", {"kind":"can_use_named_attack_if_tera","attackName":"Double-Edge"}],
  ["you must discard a chill teaser toy card from your hand in order to use this ability.", {"kind":"require_discard_named_for_ability","nameFilter":"chill teaser toy"}],
  ["during pokémon checkup, put 3 more damage counters on your opponent's burned pokémon.", {"kind":"burn_checkup_extra","extra":3}],
  ["attach a basic energy card from your discard pile to 1 of your pokémon.", {"kind":"attach_energy_from_discard","count":1,"energyType":"Any","target":"any_yours"}],
  ["if you have the same number of cards in your hand as your opponent, ignore all energy in the cost of frightening howl used by this pokémon.", {"kind":"ignore_energy_cost_if_hand_equal","attackName":"frightening howl"}],
  ["(existing effects are not removed.", null],
  ["damage is not an effect.)", null],
  ["when 1 of your water pokémon is knocked out by damage from an attack from your opponent's pokémon, you may put all basic water energy attached to that pokémon into your hand instead of the discard pile.", {"kind":"return_energy_on_ko_water"}],
  ["whenever your opponent plays a pokémon from their hand to evolve 1 of their pokémon, put 4 damage counters on that pokémon.", {"kind":"counter_on_opponent_evolve","counters":4}],
  ["during pokémon checkup, if this pokémon is in the active spot, put 2 damage counters on each of your opponent's basic pokémon.", {"kind":"checkup_counters_on_opponent_basic","counters":2}],
  ["you must discard 2 cards from your hand in order to use this ability.", {"kind":"require_discard_hand_count_for_ability","count":2}],
  ["each basic grass energy attached to all of your pokémon provides grassgrass energy.", {"kind":"grass_energy_provides_double"}],
  ["when your mega latias ex moves from your bench to the active spot, you may use this ability.", null],
  ["make your opponent's active pokémon confused.", {"kind":"status","status":"Confused","target":"opponent_active"}],
  ["if you have any darkness mega evolution pokémon ex in play, attacks used by this pokémon do 120 more damage to your opponent's active pokémon (before applying weakness and resistance).", {"kind":"self_conditional_attack_bonus","amount":120,"condition":"darkness_mega"}],
  ["each player draws a card.", {"kind":"draw_both_players","count":1}],
  ["attacks used by this pokémon do 30 more damage to your opponent's active pokémon for each prize card your opponent has taken (before applying weakness and resistance).", {"kind":"self_attack_bonus_per_opponent_prize","perPrize":30}],
  ["attach an energy card from your hand to your active larry's pokémon.", {"kind":"attach_hand_energy_to_active_named","nameFilter":"larry's"}],
  ["your opponent shuffles their hand and puts it on the bottom of their deck.", {"kind":"opponent_shuffle_hand_to_deck_bottom"}],
  ["discard a basic fire energy card from your hand in order to use this ability.", {"kind":"require_hand_energy_in_active","energyType":"Fire"}],
  ["choose a card in your hand that evolves from this pokémon and put it onto this pokémon to evolve it.", {"kind":"evolve_from_hand_in_ability"}],
  ["you can't use this ability during your first turn.", {"kind":"cant_use_ability_first_turn"}],
  ["attacks used by your opponent's active pokémon that has a pokémon tool attached do 20 less damage (before applying weakness and resistance).", {"kind":"reduce_damage_vs_tool_active","amount":20}],
  ["during your opponent's turn, if this pokémon is discarded from your deck by an effect of an attack or ability from your opponent's pokémon, or by an effect of your opponent's item or supporter cards, discard the top 8 cards of your opponent's deck.", {"kind":"mill_when_discarded_from_deck","count":8}],
  ["when your opponent's active pokémon retreats, your opponent flips a coin.", {"kind":"coin_on_opponent_retreat"}],
  ["damage counters on each pokémon (both yours and your opponent's) can't be moved to other pokémon.", {"kind":"cant_move_counters"}],
]);

export function matchBulk8Clause(clause: string): ParsedEffect[] | null {
  const key = clause.toLowerCase();
  if (!CLAUSE_MAP.has(key)) return null;
  const effect = CLAUSE_MAP.get(key);
  if (effect === null) return [];
  if (!effect) return [];
  return [effect];
}

